# Generated by Django 5.1.3 on 2024-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('EUA', 'USA'), ('BRA', 'Brazil'), ('FRANCE', 'France'), ('ISR', 'Israel'), ('CHI', 'China'), ('SKR', 'South Korea'), ('ITA', 'Italy'), ('CAN', 'Canada'), ('AUS', 'Australia'), ('UK', 'UK'), ('POL', 'Poland'), ('JPN', 'Japan')], max_length=100)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
