# Generated by Django 5.1.3 on 2024-12-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(choices=[('EUA', 'USA'), ('BRA', 'Brazil'), ('FRANCE', 'France'), ('ISR', 'Israel'), ('CHI', 'China'), ('SKR', 'South Korea'), ('ITA', 'Italy'), ('CAN', 'Canada'), ('AUS', 'Australia'), ('UK', 'UK'), ('POL', 'Poland'), ('JPN', 'Japan'), ('SAF', 'South Africa')], max_length=100),
        ),
    ]
