# Generated by Django 5.1.3 on 2025-04-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_alter_author_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('synopsis', models.CharField(blank=True, max_length=500, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(choices=[], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
