# Generated by Django 5.1.3 on 2025-05-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_nationality'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_author', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(choices=[('Panini', 'Panini'), ('Harper Collins', 'Harper Collins'), ('Rocco', 'Rocco'), ('Devir', 'Devir'), ('Mythos', 'Mythos'), ('Abril', 'Abril'), ('PN', 'Pipoca e Nanquim'), ('In', 'Intrinsseca')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
