# Generated by Django 5.1.3 on 2026-01-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_alter_book_publisher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishReadList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list_type', models.CharField(choices=[('WISH', 'wishlist'), ('READ', 'readlist')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_list', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
